%tim e_sim = 1000;
%tim e_ poruchy = 1500;
n_e1 = 0 ; 
n_e2 = 10; 
n_u = 1 ; 
lambda_u = 25;
Tvz = 1 ; 
T_q = 1 ;
lambda_y = 1 ; 
d = 3 ;
T_d = 3 ;
Gz = tf(m.B,m.A, Tvz)
Gs = d2c(Gz)
poly_z = pole(Gz)
poly_s = pole(Gs)
A = Gz.den{1};
B = Gz.num{1};
B = sum(B) ;
n_a = length(A)-1;
n_b = length(B)-1;
A_delta = conv ( [ 1 -1 ] , A) ;
[R, S , T] = RST( A_delta ,B, n_a , n_b , n_e1 , n_e2 , n_u , lambda_u , d , T_q )
K_c = S(1)-T-S(3)
K_i = T
K_d = S(3)
sim( 'RST_schema_new' )